name = "Fire"
groups = []

[[rules]]
input = "2208253656m"
output = 2256731635

[[rules.conditions]]
pattern = "2256731635m"
inverted = false

[rules.conditions.variant.Count]
Greater = 0

[[rules]]
input = "2256731635m"
output = 1972788248

[[rules.conditions]]
pattern = "2208253656m"
inverted = false

[rules.conditions.variant.Count]
Less = 1

[[rules]]
input = "1197119778m"
output = 2434385563

[[rules.conditions]]
pattern = "2256731635m"
inverted = false

[rules.conditions.variant]
Directional = ["South"]

[[rules]]
input = "1197119778m"
output = 2434385563

[[rules.conditions]]
pattern = "2434385563m"
inverted = false

[rules.conditions.variant]
Directional = ["South"]

[[rules]]
input = "2434385563m"
output = 1197119778

[[rules.conditions]]
pattern = "2434385563m"
inverted = false

[rules.conditions.variant.Count]
Greater = 5

[[rules]]
input = "2434385563m"
output = 1197119778

[[rules.conditions]]
pattern = "1972788248m"
inverted = false

[rules.conditions.variant]
Directional = ["South"]

[[rules]]
input = "2434385563m"
output = 1197119778

[[rules.conditions]]
pattern = "1197119778m"
inverted = false

[rules.conditions.variant]
Directional = ["South"]

[[materials]]
id = 1197119778
name = "Air"
color = "#000000"

[[materials]]
id = 2256731635
name = "Fire"
color = "#DDAA00"

[[materials]]
id = 2208253656
name = "Wood"
color = "#964B00"

[[materials]]
id = 1972788248
name = "Ash"
color = "#444444"

[[materials]]
id = 2434385563
name = "Smoke"
color = "#888888"
