name = "Test54"

[[rules]]
input = "4208602773g"
output = 3571558840

[[rules.conditions]]
pattern = "7390237m"

[rules.conditions.variant]
Directional = ["West", "North", "South", "East"]

[[materials]]
id = 7390237
name = "Empty"
color = "#000000"

[[materials]]
id = 3970475215
name = "Red"
color = "#FF0000"

[[materials]]
id = 3571558840
name = "Blue"
color = "#000FFF"

[[materials]]
id = 62331654
name = "Brown"
color = "#512515"

[[groups]]
id = 4208602773
name = "Colors"
materials = [3571558840, 3970475215, 62331654]
