name = "Test54"
rules = []
groups = []

[[materials]]
id = 7390237
name = "Empty"
color = "#000000"

[[materials]]
id = 3970475215
name = "New"
color = "#FF0000"

[[materials]]
id = 3571558840
name = "blue"
color = "#000FFF"

[[materials]]
id = 62331654
name = "Brown"
color = "#512515"
