cells = [
    { name = "air", color = "#000000" },
    { name = "wire", color = "#AAAAAA" },
    { name = "power", color = "#FFFF00" },
    { name = "power_source", color = "#FFFFFF" },
]

rules = [
    {in = "wire", out = "power", conditions = [
        { count = "1..", type = "power_source" }
    ]},
    {in = "wire", out = "power", conditions = [
        { dirs = "n e s w", type = "power" }
    ]},
]